### ISSUE TITLE
liquid error due to nokogiri

### ISSUE THREAD

**Issue by janghj12000** [blab/nextflu#137]
Hello I am trying to run auspice using Jekyll.

My OS is windows 8.
My ruby version is 2.3.1 (the latest one).

I have no problem with installing Jekyll.

To get compiled auspice resources, I type "jekyll build" within auspice directory in command line prompt.

It tells me that nokogiri-1.6.7.2 not available.

I try to download that nokogiri with version 1.6.7.2, but it is not successful.
The error message is saying that my ruby is newer than 2.3 version.

Is downgrading my ruby is the only option?

Thank you.

**Comment by trvrb** [comment]
Try `bundle install` from within `auspice` to install https://github.com/blab/nextflu/blob/master/auspice/Gemfile. Then run `bundle exec jekyll build`.

**Comment by janghj12000** [comment]
When I type "bundle install," this is what I get

```
Installing libv8 3.16.14.13 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/l
ibv8
C:/Ruby23/bin/ruby.exe -r ./siteconf20160830-2288-12srgfb.rb extconf.rb
creating Makefile
'patch' is not recognized as an internal or external command,
operable program or batch file.
C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/libv8/patcher.rb:51:in `
block (2 levels) in patch!': failed to apply patch (RuntimeError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/libv8/patch
er.rb:49:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/libv8/patch
er.rb:49:in `block in patch!'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/libv8/patch
er.rb:45:in `open'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/libv8/patch
er.rb:45:in `patch!'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/libv8/build
er.rb:57:in `block in build_libv8!'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/libv8/build
er.rb:52:in `chdir'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/libv8/build
er.rb:52:in `build_libv8!'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.13/ext/libv8/locat
ion.rb:24:in `install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16
.14.13 for inspection.
Results logged to C:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/lib
v8-3.16.14.13/gem_make.out
Using mime-types 1.25.1
Using ref 2.0.0
Using thor 0.18.1
Using zopfli 0.0.4
Using bundler 1.12.5
Installing nokogiri 1.6.7.2

Gem::InstallError: nokogiri requires Ruby version < 2.3, >= 1.9.2.
Using simple-cloudfront-invalidator 1.1.0
Using less 2.6.0
Using configure-s3-website 1.5.5
Using dotenv 0.11.1
Using rb-inotify 0.9.7
Using jekyll-sass-converter 1.4.0
An error occurred while installing libv8 (3.16.14.13), and Bundler cannot
continue.
Make sure that `gem install libv8 -v '3.16.14.13'` succeeds before bundling.

C:\Users\tjang\Downloads\nextflu-master\nextflu-master\auspice>gem install libv8
 -v '3.16.14.3' -- --with-system-v8
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-system-v8'
This could take a while...
Successfully installed libv8-3.16.14.3
Parsing documentation for libv8-3.16.14.3
Done installing documentation for libv8 after 1 seconds
1 gem installed
```

I reference the following url
http://stackoverflow.com/questions/19673714/error-installing-libv8-error-failed-to-build-gem-native-extension

I type "gem install libv8 -v '3.16.14.3' -- --with-system-v8". 
However, it still does not work.

**Comment by trvrb** [comment]
Hmm... I'm running `ruby 2.1.1p76`. I'd generally suggest using github.com/rbenv/rbenv to manage your Ruby environment / versions. Makes it painless to switch between versions.

**Comment by trvrb** [comment]
Marking this as closed. Please let me know if you run into additional difficulty with ruby 2.1.1.
